version: '3.9'
services:
  aboutit-api:
    build:
      context: .
      dockerfile: ./AboutIt.Api/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - mongo
      - postgresdb
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      ASPNETCORE_URLS: "http://+:80"
      ASPNETCORE_HTTP_PORT: "8080"
#      - ConnectionStrings:MongoDB=YOUR_MONGO_DB_CONNECTION_STRING
#      - ConnectionStrings:PostgreSQL=YOUR_POSTGRES_CONNECTION_STRING
#    command: ["dotnet", "YourApp.dll"]

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: your-mongo-username
#      MONGO_INITDB_ROOT_PASSWORD: your-mongo-password
    volumes:
      - ./mongo/data:/data/db

  postgresdb:
    image: postgres:15.2
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: AboutIt
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgresdb:/var/lib/postgresql/data
volumes:
  postgresdb:
    driver: local
